services:
  test:
    build:
      context: ../
      target: test

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "http"
      - "bot:8080"
      - "--authtoken=${NGROK_TOKEN}"
      - "--domain=${DOMAIN}"
    ports:
      - "4040:4040"
    env_file:
      - .env

  bot:
    image: ${DOCKERHUB_USER}/${BOT_CONTAINER_NAME}:latest
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - ngrok
      - test
