services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "http"
      - "bot:8080"
      - "--authtoken=${NGROK_TOKEN}"
      - "--domain=${DOMAIN}"
    ports:
      - "4040:4040"

  bot:
    build:
      context: ../
    restart: on-failure
    stop_signal: SIGINT
    depends_on:
      - ngrok
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ../app/:/app/bot/
