version: 1
disable_existing_loggers: false
formatters:
  simple:
    (): mylogger.ColorFormatter
    format: '%(levelname)s: %(message)s'
    datefmt: "%Y-%m-%dT%H:%M:%S%z"
  json:
    (): mylogger.MyJSONFormatter
    fmt_keys:
      level: levelname
      message: message
      timestamp: timestamp
      logger: name
      module: module
      function: funcName
      line: lineno
      thread_name: threadName
handlers:
  stdout:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
    level: INFO
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: /var/log/bot_log.jsonl
    maxBytes: 1000000
    backupCount: 3
  queue_handler:
    class: logging.handlers.QueueHandler
    handlers:
      - stdout
      - file
    respect_handler_level: true
loggers:
  root:
    level: DEBUG
    handlers:
      - queue_handler
