name: Home Bot Deploy
on:
  push:
    branches:
      - master
jobs:
  copy_compose_on_server:
    name: Copy docker compose to server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: create app folder
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USER}}
        key: ${{ secrets.SSH_KEY }}
        script: sudo rm -rf /home/${{ secrets.HOST_USER }}/bot && mkdir -p /home/${{ secrets.HOST_USER }}/bot

    - name: Copy compose file
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USER}}
        key: ${{ secrets.SSH_KEY }}
        source: "docker-compose.yml"
        target: /home/${{ secrets.HOST_USER }}/bot/
